### ISSUE TITLE
Error on Infinisdk Login while using pyinstaller to convert to Executable

### ISSUE THREAD

**Issue by daramosch** [Infinidat/infinisdk#2]
Hi Folks!

I have a Working Script to perform Automated Provisioning on Infinidat. Script works good. However due to Automation Effort I need to Convert the Script into an Executable and I'm Using pyinstaller (Which allowed me to convert an SVC Provisioning Script to executable using Paramiko) It seems that while using pyinstaller something changed on how the infinisdk login is make. 

I have Performed the following( from the Pyinstaller end)

Ran the analysis and check the warn log for module import missing.
Update the .spec file both with the --hidden-import Parameter and by updating the Spec file.
Update the .spec file with pyi-makespec --paths= with the Module Full Path name and also by updating the spec file manually
Re compile build by using the pyinstaller [file].spec.

I'm getting the following error every time. Have you seen dsomething similar?

Traceback (most recent call last):
File "LUN_Creation.py", line 3053, in 
File "LUN_Creation.py", line 662, in host_ex_AMDC_ux
File "LUN_Creation.py", line 588, in infi_login ### Above my Script , Below Error###
File "site-packages\infinisdk\infinibox\infinibox.py", line 229, in login
File "site-packages\infinisdk\infinibox\infinibox.py", line 257, in get_clien
t_id
File "site-packages\pkg_resources_init.py", line 557, in get_distribution
File "site-packages\pkg_resources_init_.py", line 431, in get_provider
File "site-packages\pkg_resources_init_.py", line 967, in require
File "site-packages\pkg_resources_init_.py", line 853, in resolve
pkg_resources.DistributionNotFound: The 'infinisdk' distribution was not found a
nd is required by the application
[322136] Failed to execute script LUN_Creation

**Comment by vmalloc** [comment]
Can you produce a minimalistic code sample to reproduce the issue? I want to rule out the possibility of this being a PyInstaller issue...

Also - what platform are you getting this on? Python version?

**Comment by daramosch** [comment]
Hi @vmalloc! I apologize you may close the issue. Sorry for consuming your time. It seems that is a problem either with some environment variable on the server I am using or with pyinstaller. I was able to kind of sort it out by compiling the executable on my PC and then distribute to my server. 
The Weird thing is that the traceback seem to be infering that the problem was with the infinibox login. 

Sorry for your trouble!

**Comment by vmalloc** [comment]
@daramosch don't worry about it! Glad you sorted it out.
